### ISSUE TITLE
No countdown for an event called "undefined"

### ISSUE THREAD

**Issue by MPV** [brianpgerson/the-count#1]
I'm not sure how I succeeded, but this is an issue I've seen just now:

![screenshot 2017-04-28 kl 13 01 13](https://cloud.githubusercontent.com/assets/62675/25526286/29c71a18-2c13-11e7-96da-2b04d9e38226.png)

**Comment by MPV** [comment]
For more context, I actually created the countdown earlier, but with a typo (an extraneous space in the name: ` 17` vs just `17`).

But after deleting the event and re-adding it with the removed space in the middle, it didn't work anymore:

![screenshot 2017-04-28 kl 13 05 37](https://cloud.githubusercontent.com/assets/62675/25526385/9e0d04f0-2c13-11e7-85d4-92d2fb13e4d6.png)

**Comment by brianpgerson** [comment]
@MPV you are the very first issue opened up here - so apologies for the delay in response! Just wanted to let you know that I'm taking a look here and will get back to you shortly with whatever I find.

**Comment by MPV** [comment]
@brianpgerson No worries. Thanks for taking the time to build and share **callie** (and for your efforts in supporting it). 😄

**Comment by brianpgerson** [comment]
Ohhhh no, you know what....this one is actually just a mismatched command. Your event is safe and sound. You just ask added an extra keyword in there.

![image](https://cloud.githubusercontent.com/assets/11603688/25785136/1a241c38-332e-11e7-92bf-dd217b747c4b.png)
^ Correct

![image](https://cloud.githubusercontent.com/assets/11603688/25785139/21ab6b5a-332e-11e7-8ebc-7ebad180deca.png)
^ callie is now looking for a countdown to `{event: Summergate17 Extreme}`.

I'm working on extending Callie's flexibility, but for now, she's a bit unforgiving with the syntax.

I'll be closing this for now. Thanks for checking in and, as always, PRs for improvements or bug fixes are welcome.

Cheers - Brian

**Comment by emitchel** [comment]
This is still an issue - need to update the command help to include `event` in the syntax is all

**Comment by brianpgerson** [comment]
You're right! my rewrite accidentally made things consistent without updating the instructions 🙈 

Thanks for letting me know. Now you can do it either way and the help response reflects that.
