### ISSUE TITLE
Schedule time zone is stuck in Pacific Time

### ISSUE THREAD

**Issue by cjdenio** [brianpgerson/the-count#12]
When I setup a schedule for a countdown, the hour I enter is seen as Pacific Time, rather than my time zone (Eastern Time). For example the command `@callie schedule: weekly, day: monday, event: My Event, hour: 3` triggers the reminder at 6:00 Eastern Time.

**Comment by brianpgerson** [comment]
Yep! Currently, all times are recorded in PST. I have no plans on updating this but if I have time I will take a crack at it because it seems like a good idea. I'll comment here if I start work on that. Otherwise, feel free to open up a PR!

**Comment by cjdenio** [comment]
I completely understand. I have a tough time finding time for projects. Soon, I hope to learn the Slack API and fix this (if you don't do it first).
