### ISSUE TITLE
Sort Events Chronologically

### ISSUE THREAD

**Issue by tredontho** [brianpgerson/the-count#13]
When adding issues, they seem to be displayed (both in reminders and via the `list` command) in the order the events were added.  It would be nice (not sure if better would be the right word) to see them sorted chronologically.

Example of current behavior:
`@callie list`

Your events:
1: Auntie Em's Birthday on 03/12/2020
2: Trip to Paris on 11/13/2019
3: Going away party for Ed from Accounting on 09/13/2019

What (I think) would look more intuitive:
`@callie list`

Your events:
1: Going away party for Ed from Accounting on 09/13/2019
2: Trip to Paris on 11/13/2019
3: Auntie Em's Birthday on 03/12/2020

**Comment by brianpgerson** [comment]
This is a good idea! I'll keep it open here in case anyone wants to open up a PR, otherwise I'll get to it when I have some time.
