### ISSUE TITLE
Adding Callie to another Channel

### ISSUE THREAD

**Issue by lespinalrivera** [brianpgerson/the-count#2]
It seems that Callie can only be in one channel at a time, when I added it to another Channel, it was gone from the original one (Which makes sense, a dog cannot be in two places at the same time :smile: )

**Comment by brianpgerson** [comment]
That is odd...I have callie in three channels on my own slack team! 

Can you let me know what your team name is?

**Comment by lespinalrivera** [comment]
Never mind, now it is barking at both channels, it seems it needed time to get used to the new channel.
