### ISSUE TITLE
After correctly setting up the daily schedule, I don't get reminders.

### ISSUE THREAD

**Issue by 23ewrdtf** [brianpgerson/the-count#7]
After correctly setting up the daily schedule, I don't get reminders.

Can you help troubleshoot please?

**Comment by brianpgerson** [comment]
Hi there - can you give me an example of the daily scheduling you did? 

Keep in mind that callie doesn't currently give automated reminders in group chats or DMs. Her automated reminder functionality is only designed to post in public and private channels.

**Comment by cjdenio** [comment]
Try entering the time as Pacific Time. Callie interprets any entered time as Pacific.
