### ISSUE TITLE
Intermittent reminders of time left [Question]

### ISSUE THREAD

**Issue by morenoh149** [brianpgerson/the-count#9]
Hello, I'm evaluating callie to see if it can solve my problem.

I'd like a bot that I can configure to send a days-remaining message every N days. Can callie do this?

**Comment by brianpgerson** [comment]
callie can currently do weekly or daily. an every `n`day message would be doable - i can either add it to the backlog (no guarantee on when/if that would be delivered) or feel free to fork and put up a PR!
